export const videosData = [
  {
    videoId: "video01",
    title: "C Programming Full Course",
    videoUrl: "https://www.youtube.com/watch?v=irqbmMNs2Bo",
    thumbnailUrl: "https://i.ytimg.com/vi/irqbmMNs2Bo/hqdefault.jpg",
    description: "Complete C programming tutorial for beginners.",
    channelId: "ApnaCollegeOfficial",
    uploader: "Apna College",
    views: 50115782,
    likes: 693000,
    dislikes: 18427,
    uploadDate: "2022-03-06",
    category: "C",
    comments: [
      {
        commentId: "c01",
        userId: "user02",
        text: "Very clear explanation!",
        timestamp: "2022-03-11T09:20:00Z",
      },
    ],
  },

  {
    videoId: "video02",
    title: "C Pointers Explained",
    videoUrl: "https://www.youtube.com/watch?v=KJgsSFOSQv0",
    thumbnailUrl: "https://i.ytimg.com/vi/KJgsSFOSQv0/hqdefault.jpg",
    description: "Understand pointers in C with simple examples.",
    channelId: "freecodecamp",
    uploader: "freecodecamp.org",
    views: 18324275,
    likes: 234000,
    dislikes: 90,
    uploadDate: "2018-08-15",
    category: "C",
    comments: [
      {
        commentId: "c02",
        userId: "user03",
        text: "Pointers finally make sense!",
        timestamp: "2018-08-18T11:10:00Z",
      },
    ],
  },

  {
    videoId: "video03",
    title: "Every React Concept Explained in 12 Minutes",
    videoUrl: "https://www.youtube.com/watch?v=wIyHSOugGGw",
    thumbnailUrl: "https://i.ytimg.com/vi/wIyHSOugGGw/hqdefault.jpg",
    description: "Learn React programming from basics to advanced.",
    channelId: "channelCPP01",
    uploader: "Code Bootcamp",
    views: 1589534,
    likes: 66000,
    dislikes: 210,
    uploadDate: "2024-03-18",
    category: "React",
    comments: [
      {
        commentId: "c03",
        userId: "user04",
        text: "Amazing course!",
        timestamp: "2024-03-19T10:00:00Z",
      },
    ],
  },

  
  {
    videoId: "video05",
    title: "Java Full Course",
    videoUrl: "https://www.youtube.com/watch?v=xk4_1vDrzzo",
    thumbnailUrl: "https://i.ytimg.com/vi/xk4_1vDrzzo/hqdefault.jpg",
    description: "Complete Java programming course in one video.",
    channelId: "BroCodez",
    uploader: "Bro Code",
    views: 13300921,
    likes: 24000,
    dislikes: 300,
    uploadDate: "2020-09-9",
    category: "Java",
    comments: [
      {
        commentId: "c05",
        userId: "user06",
        text: "Best Java tutorial!",
        timestamp: "2020-09-10T12:30:00Z",
      },
    ],
  },

  {
    videoId: "video06",
    title: "Java OOP Concepts",
    videoUrl: "https://www.youtube.com/watch?v=6T_HgnjoYwM",
    thumbnailUrl: "https://i.ytimg.com/vi/6T_HgnjoYwM/hqdefault.jpg",
    description: "Object-oriented programming concepts in Java.",
    channelId: "SimplilearnOfficial",
    uploader: "Simplilearn",
    views: 504412,
    likes: 11300,
    dislikes: 95,
    uploadDate: "2021-03-16",
    category: "Java",
    comments: [
      {
        commentId: "c06",
        userId: "user07",
        text: "Very well explained.",
        timestamp: "2021-03-17T07:50:00Z",
      },
    ],
  },

  {
    videoId: "video07",
    title: "Python for Beginners",
    videoUrl: "https://www.youtube.com/watch?v=_uQrJ0TkZlc",
    thumbnailUrl: "https://i.ytimg.com/vi/_uQrJ0TkZlc/hqdefault.jpg",
    description: "Python basics for absolute beginners.",
    channelId: "programmingwithmosh",
    uploader: "Programming with Mosh",
    views: 46708721,
    likes: 125940,
    dislikes: 420,
    uploadDate: "2019-02-18",
    category: "Python",
    comments: [
      {
        commentId: "c07",
        userId: "user08",
        text: "Perfect for beginners.",
        timestamp: "2019-02-26T06:30:00Z",
      },
    ],
  },

  {
    videoId: "video08",
    title: "Python Tutorial for Beginners 4: Lists, Tuples, and Sets",
    videoUrl: "https://www.youtube.com/watch?v=W8KRzm-HUcc",
    thumbnailUrl: "https://i.ytimg.com/vi/W8KRzm-HUcc/hqdefault.jpg",
    description: "Learn lists and tuples in Python.",
    channelId: "coreyms",
    uploader: "Corey Schafer",
    views: 1703124,
    likes: 40000,
    dislikes: 130,
    uploadDate: "2017-05-17",
    category: "Python",
    comments: [
      {
        commentId: "c08",
        userId: "user09",
        text: "Simple and effective.",
        timestamp: "2017-03-19T09:40:00Z",
      },
    ],
  },

  {
    videoId: "video09",
    title: "ExpressJS Crash Course",
    videoUrl: "https://www.youtube.com/watch?v=L72fhGm1tfE",
    thumbnailUrl: "https://i.ytimg.com/vi/L72fhGm1tfE/hqdefault.jpg",
    description: "Build REST APIs using ExpressJS.",
    channelId: "TraversyMedia",
    uploader: "Traversy Media",
    views: 989511,
    likes: 20000,
    dislikes: 160,
    uploadDate: "2019-02-22",
    category: "ExpressJS",
    comments: [
      {
        commentId: "c09",
        userId: "user10",
        text: "Very practical tutorial.",
        timestamp: "2029-02-23T10:10:00Z",
      },
    ],
  },

  {
    videoId: "video10",
    title: "NodeJS Crash Course",
    videoUrl: "https://www.youtube.com/watch?v=fBNz5xF-Kx4",
    thumbnailUrl: "https://i.ytimg.com/vi/fBNz5xF-Kx4/hqdefault.jpg",
    description: "Learn NodeJS fundamentals.",
    channelId: "TraversyMedia",
    uploader: "Traversy Media",
    views: 1693609,
    likes: 35000,
    dislikes: 250,
    uploadDate: "2019-02-07",
    category: "NodeJS",
    comments: [
      {
        commentId: "c10",
        userId: "user11",
        text: "Great NodeJS intro!",
        timestamp: "2019-02-23T11:15:00Z",
      },
    ],
  },

  {
    videoId: "video11",
    title: "HTML Full Course",
    videoUrl: "https://www.youtube.com/watch?v=pQN-pnXPaVg",
    thumbnailUrl: "https://i.ytimg.com/vi/pQN-pnXPaVg/hqdefault.jpg",
    description: "Complete HTML tutorial for web development.",
    channelId: "freeCodeCamp",
    uploader: "freeCodeCamp.org",
    views: 7607519,
    likes: 175000,
    dislikes: 310,
    uploadDate: "2018-07-18",
    category: "HTML",
    comments: [
      {
        commentId: "c11",
        userId: "user12",
        text: "Very helpful!",
        timestamp: "2018-07-22T08:00:00Z",
      },
    ],
  },

  {
    videoId: "video12",
    title: "CSS Flexbox & Grid",
    videoUrl: "https://www.youtube.com/watch?v=JJSoEo8JSnc",
    thumbnailUrl: "https://i.ytimg.com/vi/JJSoEo8JSnc/hqdefault.jpg",
    description: "Master Flexbox and Grid layouts.",
    channelId: "TraversyMedia",
    uploader: "Traversy Media",
    views: 1847000,
    likes: 42000,
    dislikes: 180,
    uploadDate: "2016-12-09",
    category: "CSS",
    comments: [
      {
        commentId: "c12",
        userId: "user13",
        text: "Layout finally understood.",
        timestamp: "2016-12-11T07:30:00Z",
      },
    ],
  },

  {
    videoId: "video13",
    title: "MongoDB Full Course",
    videoUrl: "https://www.youtube.com/watch?v=ofme2o29ngU",
    thumbnailUrl: "https://i.ytimg.com/vi/ofme2o29ngU/hqdefault.jpg",
    description: "Learn MongoDB from scratch.",
    channelId: "WebDevSimplified",
    uploader: "Web Dev Simplified",
    views: 856747,
    likes: 24000,
    dislikes: 240,
    uploadDate: "2021-09-18",
    category: "MongoDB",
    comments: [
      {
        commentId: "c13",
        userId: "user14",
        text: "Excellent MongoDB explanation.",
        timestamp: "2021-09-31T06:50:00Z",
      },
    ],
  },

  {
    videoId: "video14",
    title: "🎮 How to Become a Game Developer | Complete Roadmap for Game Development 🎮",
    videoUrl: "https://www.youtube.com/watch?v=qPxvmrtTQ_4",
    thumbnailUrl: "https://i.ytimg.com/vi/qPxvmrtTQ_4/hqdefault.jpg",
    description: "Comment #HarryBhai if you read this 😉😉",
    channelId: "CodeWithHarry",
    uploader: "CodeWithHarry",
    views: 1026612,
    likes: 34000,
    dislikes: 125,
    uploadDate: "2024-03-17",
    category: "Gaming",
    comments: [
      {
        commentId: "c14",
        userId: "user15",
        text: "Childhood memories!",
        timestamp: "2024-03-18T14:20:00Z",
      },
    ],
  },

  {
    videoId: "video15",
    title: "BECOME A GAME DEVELOPER IN 3 MONTHS | 3 MONTH GAME DEVELOPMENT LEARNING PLAN (Urdu/Hindi)",
    videoUrl: "https://www.youtube.com/watch?v=TgfKGT7_ID0",
    thumbnailUrl: "https://i.ytimg.com/vi/TgfKGT7_ID0/hqdefault.jpg",
    description: "BECOME A GAME DEVELOPER IN 3 MONTHS | 3 MONTH GAME DEVELOPMENT LEARNING PLAN (Urdu/Hindi)",
    channelId: "nafay3d",
    uploader: "Nafay 3D",
    views: 51399,
    likes: 26000,
    dislikes: 102,
    uploadDate: "2024-12-04",
    category: "Gaming",
    comments: [
      {
        commentId: "c15",
        userId: "user16",
        text: "Good job Love from india❤❤",
        timestamp: "2024-12-09T15:40:00Z",
      },
    ],
  },
];